### ISSUE TITLE
The Creator of this mod being unethical dumbass

### ISSUE THREAD

**Issue by kernelxdev** [Egor935/SR2MP#8]
Creator is taking donations and not updating the mod he scammed probably like 100 people that were thinking this mod is going to come out. He has literally almost 0 coding skills literally copying code. And also bro is not doing the slightest to hide it. If you are reading this stop doing whatever you are doing or I will take action. 👍

**Comment by TheanMcGarity** [comment]
Agree.

**Comment by Egor935** [comment]
Thanks for your issue report! I will fix it in the next update as soon as possible!

**Comment by MadMincraftr** [comment]
hey, so i take back everything ive said, im so sorry
